from fpdf import FPDF
from datetime import date
from threat_scorer import assess_threat_level
from rss_processor import get_clean_alerts
from plan_rules import PLAN_RULES
import json
import os
from dotenv import load_dotenv
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from email.mime.text import MIMEText
from chat_handler import get_plan
from translator import translate_text

load_dotenv()

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

# ✅ Generate Translated PDF Report
def generate_translated_pdf(email, alerts, plan, language="en"):
    class PDF(FPDF):
        def header(self):
            self.set_font("Noto", "B", 16)
            self.set_text_color(237, 0, 0)
            heading = translate_text("Sentinel AI Daily Brief", target_lang=language)
            self.cell(0, 10, f"{heading} — {date.today().isoformat()}", ln=True, align='C')
            self.ln(10)

        def chapter_body(self, alerts):
            for alert in alerts:
                self.set_text_color(0)
                self.set_font("Noto", "B", 12)
                self.multi_cell(0, 10, f"{alert['title']}", align='L')

                level_color = get_threat_color(alert["level"])
                self.set_text_color(100, 100, 100)
                self.set_font("Noto", "I", 11)
                src_label = translate_text("Source", target_lang=language)
                self.cell(0, 8, f"{src_label}: {alert['source']}", ln=True)

                self.set_text_color(*level_color)
                level_label = translate_text("Threat Level", target_lang=language)
                self.cell(0, 8, f"{level_label}: {alert['level']}", ln=True)

                self.set_text_color(0)
                self.set_font("Noto", "", 12)
                self.multi_cell(0, 10, f"{alert['summary']}", align='L')

                if alert["link"]:
                    self.set_text_color(0, 0, 255)
                    self.set_font("Noto", "", 11)
                    self.set_underline(True)
                    self.cell(0, 10, alert["link"], ln=True, link=alert["link"])
                    self.set_underline(False)

                self.set_font("Noto", "", 12)
                self.set_text_color(0)
                self.ln(6)

    def get_threat_color(level):
        if level == "Low":
            return (0, 150, 0)
        elif level == "Moderate":
            return (255, 165, 0)
        elif level == "High":
            return (255, 0, 0)
        elif level == "Critical":
            return (139, 0, 0)
        else:
            return (100, 100, 100)

    scored_alerts = []
    for alert in alerts:
        title = translate_text(alert["title"], target_lang=language)
        summary = translate_text(alert["summary"], target_lang=language)
        try:
            level = assess_threat_level(f"{title}: {summary}")
        except:
            level = "Unrated"
        scored_alerts.append({
            "title": title,
            "summary": summary,
            "source": alert["source"],
            "link": alert["link"],
            "level": level
        })

    pdf = PDF()
    pdf.add_font("Noto", "", "fonts/NotoSans-Regular.ttf", uni=True)
    pdf.add_font("Noto", "B", "fonts/NotoSans-Regular.ttf", uni=True)
    pdf.add_font("Noto", "I", "fonts/NotoSans-Regular.ttf", uni=True)

    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.chapter_body(scored_alerts)

    filename = f"report_{email}_{language}_{date.today().isoformat()}.pdf"
    pdf.output(filename)
    return filename

# ✅ Email PDF to Client
def send_pdf_report(email, plan, language="en"):
    if not PLAN_RULES.get(plan, {}).get("pdf", False):
        raise PermissionError(f"❌ {plan} plan does not allow PDF report access.")

    alerts = get_clean_alerts()
    pdf_file = generate_translated_pdf(email, alerts, plan, language)

    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = email
    msg["Subject"] = f"Sentinel AI Report — {plan} Plan"

    body = translate_text(
        f"Attached is your travel safety report generated by Sentinel AI ({plan} Plan). Stay safe and informed.",
        target_lang=language
    )
    msg.attach(MIMEText(body, "plain"))

    with open(pdf_file, "rb") as f:
        part = MIMEApplication(f.read(), Name=pdf_file)
        part['Content-Disposition'] = f'attachment; filename="{pdf_file}"'
        msg.attach(part)

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(SENDER_EMAIL, SENDER_PASSWORD)
    server.send_message(msg)
    server.quit()

    os.remove(pdf_file)
    return True

# ✅ Send to All Clients
def send_daily_summaries():
    with open("clients.json", "r") as f:
        clients = json.load(f)

    for client in clients:
        email = client["email"]
        plan = client.get("plan", "FREE")
        language = client.get("lang", "en")  # ✅ Use 'lang' as the consistent key
        try:
            if PLAN_RULES.get(plan, {}).get("pdf", False):
                send_pdf_report(email=email, plan=plan, language=language)
                print(f"✅ Sent report to {email} ({plan}, {language})")
            else:
                print(f"⏩ Skipped {email} — no PDF access ({plan})")
        except Exception as e:
            print(f"❌ Error sending to {email}: {str(e)}")
