# Major cities/local news feeds (100+ cities globally)
LOCAL_FEEDS = {
    "belgrade": ["https://www.blic.rs/rss/Vesti/Drustvo"],
    "hong kong": ["https://www.scmp.com/rss/2/feed/"],
    "paris": ["https://www.lemonde.fr/rss/une.xml"],
    "new york": ["https://nypost.com/tag/new-york-city/feed/"],
    "los angeles": ["https://www.latimes.com/local/rss2.0.xml"],
    "mumbai": ["https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms"],
    "moscow": ["https://www.themoscowtimes.com/rss/news"],
    "sydney": ["https://www.abc.net.au/news/feed/2942460/rss.xml"],
    "rome": ["https://www.romatoday.it/rss"],
    "delhi": ["https://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms"],
    "saopaulo": ["https://g1.globo.com/rss/g1/saopaulo/"],
    "singapore": ["https://www.straitstimes.com/news/singapore/rss.xml"],
    "buenos aires": ["https://www.clarin.com/rss/lo-ultimo/"],
    "karachi": ["https://www.dawn.com/feeds/home"],
    "manila": ["https://www.philstar.com/rss/nation"],
    "boston": ["https://www.boston.com/tag/local-news/feed/"],
    "washington": ["https://wtop.com/local/feed/"],
    "miami": ["https://www.miamiherald.com/news/local/?widgetName=rssfeed&widgetId=1159003&getXmlFeed=true"],
    "dallas": ["https://www.dallasnews.com/news/rss/"],
    "atlanta": ["https://www.ajc.com/news/local/rss/"],
    "barcelona": ["https://www.lavanguardia.com/rss/barcelona.xml"],
    "amsterdam": ["https://www.parool.nl/amsterdam/rss.xml"],
    "vienna": ["https://www.derstandard.at/rss/international"],
    "zurich": ["https://www.nzz.ch/rss"],
    "brussels": ["https://www.brusselstimes.com/feed"],
    "stockholm": ["https://www.thelocal.se/stockholm/rss"],
    "oslo": ["https://www.aftenposten.no/rss"],
    "helsinki": ["https://www.hs.fi/rss/tuoreimmat.xml"],
    "copenhagen": ["https://www.dr.dk/nyheder/service/feeds/allenyheder"],
    "prague": ["https://english.radio.cz/rss"],
    "budapest": ["https://dailynewshungary.com/feed/"],
    "warsaw": ["https://www.thefirstnews.com/rss"],
    "bucharest": ["https://www.romania-insider.com/rss"],
    "sofia": ["https://www.novinite.com/rss.php"],
    "athens": ["https://www.ekathimerini.com/rss"],
    "ankara": ["https://www.hurriyet.com.tr/rss/ankara"],
    "cologne": ["https://www.ksta.de/koeln/rss.xml"],
    "munich": ["https://www.sueddeutsche.de/rss/Topthemen"],
    "saint petersburg": ["https://spbdnevnik.ru/rss/all.rss"],
    "kyiv": ["https://www.kyivpost.com/feed"],
    "minsk": ["https://eng.belta.by/rss_en"],
    "tel aviv": ["https://www.jpost.com/rss/rssfeedsfrontpage.aspx"],
    "dubai": ["https://gulfnews.com/rss/1.454509"],
    "riyadh": ["https://english.alarabiya.net/tools/rss"],
    "tehran": ["https://www.tehrantimes.com/rss"],
    "baghdad": ["https://www.iraqinews.com/feed/"],
    "beirut": ["https://www.dailystar.com.lb/RSS.aspx?id=1"],
    "damascus": ["http://sana.sy/en/?feed=rss2"],
    "cali": ["https://www.elpais.com.co/rss/colombia.xml"],
    "lima": ["https://elcomercio.pe/feed/"],
    "caracas": ["https://www.eluniversal.com/rss/rss.xml"],
    "bogota": ["https://www.eltiempo.com/rss/bogota.xml"],
    "cape town": ["https://www.iol.co.za/cmlink/1.640"],
    "nairobi": ["https://www.nation.co.ke/rss.xml"],
    "casablanca": ["https://www.moroccoworldnews.com/feed"],
    "algiers": ["https://www.aps.dz/en/rss"],
    "addis ababa": ["https://addisstandard.com/feed/"],
    "lagos": ["https://thenationonlineng.net/feed/"],
    "accra": ["https://www.ghanaweb.com/GhanaHomePage/NewsArchive/rss"],
    "abidjan": ["https://www.fratmat.info/rss.xml"],
    "cotonou": ["https://beninwebtv.com/feed/"],
    "kinshasa": ["https://www.radiookapi.net/rss.xml"],
    "jeddah": ["https://english.alarabiya.net/tools/rss"],
    "doha": ["https://www.gulf-times.com/rss"],
    "kuwait city": ["https://www.arabtimesonline.com/news/rss/"],
    "singapore": ["https://www.straitstimes.com/news/singapore/rss.xml"],
    "kuala lumpur": ["https://www.nst.com.my/rss"],
    "bangkok": ["https://www.bangkokpost.com/rss/data/topstories.xml"],
    "hanoi": ["https://vietnamnews.vn/rss"],
    "jakarta": ["https://www.thejakartapost.com/rss"],
    "manila": ["https://www.philstar.com/rss/nation"],
    "melbourne": ["https://www.abc.net.au/news/feed/2942460/rss.xml"],
    "auckland": ["https://www.nzherald.co.nz/news/rss.xml"],
    "perth": ["https://thewest.com.au/feed"],
    "sydney": ["https://www.abc.net.au/news/feed/2942460/rss.xml"],
    "brisbane": ["https://www.brisbanetimes.com.au/rss/feed.xml"],
    "montreal": ["https://montrealgazette.com/feed/"],
    "vancouver": ["https://vancouversun.com/feed/"],
    "calgary": ["https://calgaryherald.com/feed/"],
    "ottawa": ["https://ottawacitizen.com/feed/"],
    "toronto": ["https://www.cp24.com/rss/cp24-news-rss-1.5859135"],
    "edmonton": ["https://edmontonjournal.com/feed/"],
    "quebec city": ["https://www.quebechebdo.com/feed/"],
    "winnipeg": ["https://winnipegsun.com/feed/"],
    "halifax": ["https://globalnews.ca/halifax/feed/"],
    "st johns": ["https://www.cbc.ca/cmlink/rss-canada-newfoundlandandlabrador"],
    "cape town": ["https://www.iol.co.za/cmlink/1.640"],
}

# Country-level news feeds for fallback
COUNTRY_FEEDS = {
    "united kingdom": ["https://feeds.bbci.co.uk/news/uk/rss.xml"],
    "france": ["https://www.france24.com/en/rss"],
    "germany": ["https://www.dw.com/en/top-stories/germany/rss"],
    "united states": ["https://rss.nytimes.com/services/xml/rss/nyt/US.xml"],
    "canada": ["https://www.cbc.ca/cmlink/rss-canada"],
    "australia": ["https://www.abc.net.au/news/feed/51120/rss.xml"],
    "japan": ["https://www3.nhk.or.jp/nhkworld/en/news/feeds/rss.xml"],
    "china": ["http://www.chinadaily.com.cn/rss/china_rss.xml"],
    "india": ["https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"],
    "brazil": ["https://g1.globo.com/rss/g1/"],
    "south africa": ["https://www.news24.com/news24/rss"],
    "russia": ["https://www.themoscowtimes.com/rss/news"],
    "mexico": ["https://www.eluniversal.com.mx/rss/nacion.xml"],
    "argentina": ["https://www.clarin.com/rss/lo-ultimo/"],
    "turkey": ["https://www.hurriyet.com.tr/rss/gundem"],
    "spain": ["https://elpais.com/rss/elpais/portada.xml"],
    "italy": ["https://www.ansa.it/sito/ansait_rss.xml"],
    "egypt": ["https://english.ahram.org.eg/NewsRSS.aspx?CategoryID=3"],
    "nigeria": ["https://thenationonlineng.net/feed/"],
    "kenya": ["https://www.nation.co.ke/rss.xml"],
    "indonesia": ["https://www.thejakartapost.com/rss"],
    "thailand": ["https://www.bangkokpost.com/rss/data/topstories.xml"],
    "philippines": ["https://www.philstar.com/rss/nation"],
    "south korea": ["https://koreajoongangdaily.joins.com/newslist/rss.aspx"],
    "pakistan": ["https://www.dawn.com/feeds/home"],
    "colombia": ["https://www.eltiempo.com/rss/colombia.xml"],
    "peru": ["https://elcomercio.pe/feed/"],
    "chile": ["https://www.latercera.com/rss/feed/"],
    "vietnam": ["https://vietnamnews.vn/rss"],
    "malaysia": ["https://www.nst.com.my/rss"],
    "singapore": ["https://www.straitstimes.com/news/singapore/rss.xml"],
    "saudi arabia": ["https://english.alarabiya.net/tools/rss"],
    "iran": ["https://www.tehrantimes.com/rss"],
    "iraq": ["https://www.iraqinews.com/feed/"],
    "syria": ["http://sana.sy/en/?feed=rss2"],
    "lebanon": ["https://www.dailystar.com.lb/RSS.aspx?id=1"],
    "israel": ["https://www.jpost.com/rss/rssfeedsfrontpage.aspx"],
    "uae": ["https://gulfnews.com/rss/1.454509"],
    "qatar": ["https://www.gulf-times.com/rss"],
    "kuwait": ["https://www.arabtimesonline.com/news/rss/"],
    "morocco": ["https://www.moroccoworldnews.com/feed"],
    "algeria": ["https://www.aps.dz/en/rss"],
    "ethiopia": ["https://addisstandard.com/feed/"],
    "ghana": ["https://www.ghanaweb.com/GhanaHomePage/NewsArchive/rss"],
    "ivory coast": ["https://www.fratmat.info/rss.xml"],
    "benin": ["https://beninwebtv.com/feed/"],
    "dr congo": ["https://www.radiookapi.net/rss.xml"],
    "belgium": ["https://www.brusselstimes.com/feed"],
    "netherlands": ["https://www.dutchnews.nl/feed/"],
    "sweden": ["https://www.thelocal.se/rss"],
    "norway": ["https://www.aftenposten.no/rss"],
    "denmark": ["https://www.dr.dk/nyheder/service/feeds/allenyheder"],
    "finland": ["https://www.hs.fi/rss/tuoreimmat.xml"],
    "switzerland": ["https://www.nzz.ch/rss"],
    "austria": ["https://www.derstandard.at/rss/international"],
    "czech republic": ["https://english.radio.cz/rss"],
    "hungary": ["https://dailynewshungary.com/feed/"],
    "poland": ["https://www.thefirstnews.com/rss"],
    "romania": ["https://www.romania-insider.com/rss"],
    "bulgaria": ["https://www.novinite.com/rss.php"],
    "greece": ["https://www.ekathimerini.com/rss"],
    "ukraine": ["https://www.kyivpost.com/feed"],
    "belarus": ["https://eng.belta.by/rss_en"],
    # More can be added as needed...
}

# Global news/alerts for fallback
GLOBAL_FEEDS = [
    "https://www.cisa.gov/news.xml",
    "https://www.darkreading.com/rss.xml",
    "https://krebsonsecurity.com/feed/",
    "https://www.bleepingcomputer.com/feed/",
    "https://www.securitymagazine.com/rss/",
    "https://feeds.feedburner.com/TheHackersNews",
    "https://www.csoonline.com/feed/",
    "https://intel471.com/blog/feed",
    "https://www.aljazeera.com/xml/rss/all.xml",
    "https://www.gov.uk/foreign-travel-advice.atom",
]